<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Redacteur extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Redacteur_model');
    } 

    /*
     * Listing of tb_redacteurs
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tb_redacteur/index?');
        $config['total_rows'] = $this->Redacteur_model->get_all_tb_redacteurs_count();
        $this->pagination->initialize($config);

        $data['tb_redacteurs'] = $this->Redacteur_model->get_all_tb_redacteurs($params);
        
        $data['_view'] = 'redacteur/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_redacteur
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('redacteur_specialite','Redacteur Specialite','required|max_length[75]');
		$this->form_validation->set_rules('redacteur_nom','Redacteur Nom','max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'redacteur_specialite' => $this->input->post('redacteur_specialite'),
				'date_creation' => $this->input->post('date_creation'),
				'redacteur_nom' => $this->input->post('redacteur_nom'),
				'redacteur_adresse' => $this->input->post('redacteur_adresse'),
            );
            
            $tb_redacteur_id = $this->Redacteur_model->add_tb_redacteur($params);
            redirect('redacteur/index');
        }
        else
        {            
            $data['_view'] = 'redacteur/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_redacteur
     */
    function edit($redacteur_id)
    {   
        // check if the tb_redacteur exists before trying to edit it
        $data['tb_redacteur'] = $this->Redacteur_model->get_tb_redacteur($redacteur_id);
        
        if(isset($data['tb_redacteur']['redacteur_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('redacteur_specialite','Redacteur Specialite','required|max_length[75]');
			$this->form_validation->set_rules('redacteur_nom','Redacteur Nom','max_length[255]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'redacteur_specialite' => $this->input->post('redacteur_specialite'),
					'date_creation' => $this->input->post('date_creation'),
					'redacteur_nom' => $this->input->post('redacteur_nom'),
					'redacteur_adresse' => $this->input->post('redacteur_adresse'),
                );

                $this->Redacteur_model->update_tb_redacteur($redacteur_id,$params);            
                redirect('redacteur/index');
            }
            else
            {
                $data['_view'] = 'redacteur/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_redacteur you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_redacteur
     */
    function remove($redacteur_id)
    {
        $tb_redacteur = $this->Redacteur_model->get_tb_redacteur($redacteur_id);

        // check if the tb_redacteur exists before trying to delete it
        if(isset($tb_redacteur['redacteur_id']))
        {
            $this->Redacteur_model->delete_tb_redacteur($redacteur_id);
            redirect('redacteur/index');
        }
        else
            show_error('The tb_redacteur you are trying to delete does not exist.');
    }
    
}
