<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_category by categorie_id
     */
    function get_tb_category($categorie_id)
    {
        return $this->db->get_where('tb_categories',array('categorie_id'=>$categorie_id))->row_array();
    }
        
    /*
     * Get all tb_categories
     */
    function get_all_tb_categories()
    {
        $this->db->order_by('categorie_id', 'desc');
        return $this->db->get('tb_categories')->result_array();
    }
        
    /*
     * function to add new tb_category
     */
    function add_tb_category($params)
    {
        $this->db->insert('tb_categories',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_category
     */
    function update_tb_category($categorie_id,$params)
    {
        $this->db->where('categorie_id',$categorie_id);
        return $this->db->update('tb_categories',$params);
    }
    
    /*
     * function to delete tb_category
     */
    function delete_tb_category($categorie_id)
    {
        return $this->db->delete('tb_categories',array('categorie_id'=>$categorie_id));
    }
}
